using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using backend.Models;
using Microsoft.EntityFrameworkCore;
using QuestPDF;
using System.Reflection;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace backend.services;

public class ReportService
{
  private readonly FinancetrackerContext _db;

  public ReportService(FinancetrackerContext db)
  {
    _db = db;
  }

  public async Task<byte[]> GenerateBudgetReportPdfAsync(Guid userId, DateTime from, DateTime to, CancellationToken ct = default)
  {
    var budgets = await _db.Budgets
        .Where(b => b.UserId == userId)
        .Include(b => b.Category)
        .ToListAsync(ct);

    var transactions = await _db.Transactions
        .Where(t => t.UserId == userId && t.Date >= from && t.Date <= to)
        .ToListAsync(ct);

    var doc = Document.Create(container =>
        {
          container.Page(page =>
          {
            page.Size(PageSizes.A4);
            page.Margin(20);
            page.PageColor(Colors.White);
            page.DefaultTextStyle(x => x.FontSize(11));

            page.Header().Text($"FinanceTracker report — {from:yyyy-MM-dd} — {to:yyyy-MM-dd}").SemiBold().FontSize(16);

            page.Content().Column(col =>
              {
                col.Item().Text("Budgets summary").Bold().FontSize(13);

                if (!budgets.Any())
                {
                  col.Item().Text("No budgets found");
                }
                else
                {
                  foreach (var b in budgets)
                  {
                    var spent = transactions.Where(t => t.CategoryId == b.CategoryId && t.Date >= (b.StartDate ?? from) && t.Date <= (b.EndDate ?? to)).Sum(t => t.Amount);
                    col.Item().Row(r =>
                      {
                        var left = r.RelativeItem();
                        left.Text(b.Name ?? "(no name)");

                        r.ConstantItem(120).AlignRight().Text($"Budget: {b.Amount:C}");

                        r.ConstantItem(120).AlignRight().Text($"Spent: {spent:C}");
                      });
                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                  }
                }

                col.Item().PageBreak();

                col.Item().Text("Transactions").Bold().FontSize(13);
                if (!transactions.Any())
                {
                  col.Item().Text("No transactions in period");
                }
                else
                {
                  foreach (var t in transactions.OrderByDescending(t => t.Date))
                  {
                    col.Item().Row(r =>
                        {
                          r.ConstantItem(120).Text(t.Date?.ToString("yyyy-MM-dd") ?? "");

                          var desc = r.RelativeItem();
                          desc.Text(t.Description ?? t.Name ?? "");

                          r.ConstantItem(100).AlignRight().Text(string.Format("{0:C}", t.Amount));
                        });
                  }
                }
              });

            page.Footer().AlignCenter().Text("Generated by FinanceTracker");
          });
        });

    using var ms = new MemoryStream();
    doc.GeneratePdf(ms);
    return ms.ToArray();
  }
}
