flowchart LR
  AddCategory[Add Category Page]
  AppLayout[AppLayout]
  AddCategoryForm[AddCategoryForm]
  IconSelector[IconSelector]
  CategoryAPI[apis/Category.ts]
  Http[httpservice]

  AddCategory --> AppLayout
  AddCategory --> AddCategoryForm
  AddCategory --> IconSelector

  AddCategoryForm --> CategoryAPI
  CategoryAPI --> Http
