sequenceDiagram
    participant Client
    participant API as /api/categories
    participant AuthorizationMiddleware
    participant Db as FinancetrackerContext

    Client->>API: DELETE /api/categories/{id}
    API->>AuthorizationMiddleware: validate token -> get userId
    API->>Db: SELECT category
    Db-->>API: category
    API->>Db: If owner delete
    Db-->>API: removed
    API-->>Client: 204 No Content
