classDiagram
    %% core domain models
    class User {
      +Guid UserId
      +string Username
      +string Email
      +string PasswordHash
      +string Salt
      +DateTime? CreatedAt
      +DateTime? ModifiedAt
    }

    class Category {
      +Guid CategoryId
      +string Name
      +string? Icon
      +string? Color
      +Guid? UserId
      +string Type
    }

    class Budget {
      +Guid BudgetId
      +Guid UserId
      +Guid? CategoryId
      +string? Name
      +DateTime? StartDate
      +DateTime? EndDate
      +DateTime? CreatedAt
      +decimal Amount
    }

    class Transaction {
      +Guid TransactionId
      +Guid UserId
      +Guid CategoryId
      +decimal Amount
      +string? Description
      +DateTime? Date
      +DateTime? CreatedAt
      +string? Name
      +Guid? SubscriptionId
    }

    class Notification {
      +Guid NotificationId
      +Guid? BudgetId
      +Guid? TransactionId
      +int Level
      +DateTime? SentAt
      +DateTime? PeriodStart
      +DateTime? PeriodEnd
    }

    %% relationships
  User "1" --> "0..*" Budget
  User "1" --> "0..*" Category
  User "1" --> "0..*" Transaction

  Category "1" --> "0..*" Budget
  Category "1" --> "0..*" Transaction

  Budget "*" --> "0..1" Category
  Budget "*" --> "1" User

  Transaction "*" --> "1" Category
  Transaction "*" --> "1" User

